### ISSUE TITLE
register copying?

### ISSUE THREAD

**Issue by Yhprum** [izumariu/puberty#1]
I love this language! Having so much fun messing around with it - you should make more commands! One thing that I notice that I was missing was being able to copy the value in one register into another - maybe a command that does something like REGS[REGPTR+1] = REGS[REGPTR] or have it always go to $F

**Comment by izumariu** [comment]
Hey, thanks a bunch! I was thinking about that, maybe I can implement it in the future! If you have any ideas feel free to contact me!

**Comment by JulianMcOmie** [comment]
I don't know if this is just me, but I always get the error "OOPS WRONG SYNTAX IN FOURTH INTRO SENTENCE ("Then he spots fatfurs") when running helloworld.fap. But it doesn't just stop working for that file. No matter if I use correct syntax or other files, it always happens. Maybe I'm doing something wrong, but idk.
